# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-07 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uesr',
            new_name='user',
        ),
    ]
